pdc/urls.py
#
# Copyright (c) 2015 Red Hat
# Licensed under The MIT License (MIT)
# http://opensource.org/licenses/MIT
#
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from pdc.apps.utils.SortedRouter import router
from django.utils.module_loading import autodiscover_modules

from pdc.apps.release.views import ReleaseListView, ReleaseDetailView
from pdc.apps.release.views import BaseProductListView, BaseProductDetailView
from pdc.apps.release.views import ProductListView, ProductDetailView
from pdc.apps.release.views import ProductVersionListView, ProductVersionDetailView
from pdc.apps.compose.views import ComposeListView, ComposeDetailView
from pdc.apps.compose.views import ComposeRPMListView, RPMOverrideFormView, ComposeImageListView
from pdc.apps.changeset.views import ChangesetListView, ChangesetDetailView
from pdc.apps.common import views as common_views
from pdc.apps.auth import views as auth_views
from pdc.apps.release import views as release_views


autodiscover_modules('routers')

urlpatterns = [
    url(r'^$', common_views.home, name='home'),

    # see details about configuring kerberos authentication in utils/auth.py
    url(r'^auth/krb5login$', auth_views.remoteuserlogin, name='auth/krb5login'),
    url(r'^auth/saml2login$', auth_views.remoteuserlogin, name='auth/saml2login'),
    url(r'^auth/logout$', auth_views.logout, name='auth/logout'),

    url(r'^admin/', admin.site.urls),
    url(r'^auth/profile/$', auth_views.user_profile, name='auth/profile'),
    url(r'^auth/refresh-ldap/$', auth_views.refresh_ldap_groups,
        name='auth/refresh_ldap'),

    url(r"^compose/$", ComposeListView.as_view(), name="compose/index"),
    url(r"^compose/(?P<id>\d+)/$", ComposeDetailView.as_view(), name="compose/detail"),

    url(r"^compose/(?P<id>\d+)/rpms/(?P<variant>[^/]+)/$", ComposeRPMListView.as_view(),
        name="compose/id/rpms/variant"),
    url(r"^compose/(?P<id>\d+)/rpms/(?P<variant>[^/]+)/(?P<arch>[^/]+)/$",
        ComposeRPMListView.as_view(), name="compose/id/rpms/variant/arch"),

    url(r"^compose/(?P<id>\d+)/images/(?P<variant>[^/]+)/$", ComposeImageListView.as_view(),
        name="compose/id/images/variant"),
    url(r"^compose/(?P<id>\d+)/images/(?P<variant>[^/]+)/(?P<arch>[^/]+)/$",
        ComposeImageListView.as_view(), name="compose/id/images/variant/arch"),

    url(r"^override/manage/(?P<release_id>[^/]+)/", RPMOverrideFormView.as_view(),
        name="override/manage"),

    url(r"^release/$", ReleaseListView.as_view(), name="release/index"),
    url(r"^release/(?P<id>\d+)/$", ReleaseDetailView.as_view(), name="release/detail"),
    url(r"^release/(?P<release_id>[^/]+)/$", ReleaseDetailView.as_view(), name="release/detail/slug"),

    url(r"^base-product/$", BaseProductListView.as_view(), name="base_product/index"),
    url(r"^base-product/(?P<id>\d+)/$", BaseProductDetailView.as_view(), name="base_product/detail"),
    url(r"^base-product/(?P<base_product_id>[^/]+)/$", BaseProductDetailView.as_view(), name="base_product/detail/slug"),

    url(r"^product/$", ProductListView.as_view(), name="product/index"),
    url(r"^product/(?P<id>\d+)/$", ProductDetailView.as_view(), name="product/detail"),
    url(r"^product/(?P<short>[^/]+)/$", ProductDetailView.as_view(), name="product/detail/slug"),
    url(r'^product-index/$', release_views.product_pages, name='product_pages'),

    url(r"^product-version/$",
        ProductVersionListView.as_view(),
        name="product_version/index"),
    url(r"^product-version/(?P<id>\d+)/$",
        ProductVersionDetailView.as_view(),
        name="product_version/detail"),
    url(r"^product-version/(?P<product_version_id>[^/]+)/$",
        ProductVersionDetailView.as_view(),
        name="product_version/detail/slug"),

    url(r"^%s%s/" % (settings.REST_API_URL, settings.REST_API_VERSION), include(router.urls)),
    url(r"^%sperms/" % settings.REST_API_URL, auth_views.api_perms, name="api-perms"),
    url(r'^changes/$', ChangesetListView.as_view(), name='changeset/list'),
    url(r'^changes/(?P<id>\d+)/$', ChangesetDetailView.as_view(), name='changeset/detail'),
]

handler404 = 'pdc.apps.common.views.handle404'

if settings.DEBUG:
    try:
        import debug_toolbar
    except ImportError:
        pass
    else:
        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

pdc/apps/release/models.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2015 Red Hat
# Licensed under The MIT License (MIT)
# http://opensource.org/licenses/MIT
#

import json

from django.db import models
from django.core.validators import RegexValidator
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError

from productmd.common import RELEASE_SHORT_RE, RELEASE_VERSION_RE
from productmd.common import create_release_id

from pdc.apps.common.hacks import as_list
from . import signals
from pdc.apps.common.models import SigKey
from pdc.apps.repository.models import PushTarget, Service


def validateCPE(cpe):
    """
    Returns None if CPE text is valid, validation error string otherwise.
    """
    if not cpe.startswith("cpe:"):
        return 'CPE must start with "cpe:"'
    return None


class ReleaseType(models.Model):
    short               = models.CharField(max_length=255, blank=False, unique=True)
    name                = models.CharField(max_length=255, blank=False, unique=True)
    suffix              = models.CharField(max_length=255, blank=True, unique=True)

    class Meta:
        ordering = ('short', 'name', 'suffix')

    def __unicode__(self):
        return u"%s" % self.short


class BaseProduct(models.Model):
    # base_product_id is populated by populate_base_product_id() pre_save hook
    base_product_id     = models.CharField(max_length=200, blank=False, unique=True)
    short = models.CharField(max_length=200, validators=[
        RegexValidator(regex=RELEASE_SHORT_RE.pattern, message='Only accept lowercase letters, numbers or -')])
    version             = models.CharField(max_length=200)
    name                = models.CharField(max_length=255)
    release_type        = models.ForeignKey(ReleaseType, blank=False, db_index=True, on_delete=models.CASCADE)

    class Meta:
        unique_together = (
            ("short", "version", "release_type"),
            ("name", "version", "release_type"),
        )
        ordering = ("base_product_id", )

    def __unicode__(self):
        return unicode(self.base_product_id)

    def get_base_product_id(self):
        return create_release_id(self.short.lower(), self.version, self.release_type.short)

    def export(self):
        return {
            "base_product_id": self.base_product_id,
            "short": self.short,
            "version": self.version,
            "name": self.name,
            "release_type": self.release_type.short,
        }


@receiver(pre_save, sender=BaseProduct)
def populate_base_product_id(sender, instance, **kwargs):
    instance.base_product_id = instance.get_base_product_id()


class Product(models.Model):
    name    = models.CharField(max_length=200)
    short = models.CharField(max_length=200, unique=True, validators=[
        RegexValidator(regex=RELEASE_SHORT_RE.pattern, message='Only accept lowercase letters, numbers or -')])

    allowed_push_targets = models.ManyToManyField(PushTarget)

    class Meta:
        ordering = ("short", )

    def __unicode__(self):
        return self.short

    @property
    def active(self):
        return self.active_release_count > 0

    @property
    def product_version_count(self):
        return self.productversion_set.count()

    @property
    def active_product_version_count(self):
        return sum(1 for pv in self.productversion_set.all() if pv.active)

    @property
    def release_count(self):
        return sum(pv.release_count for pv in self.productversion_set.all())

    @property
    def active_release_count(self):
        return sum(pv.active_release_count for pv in self.productversion_set.all())

    def export(self):
        return {
            "name": self.name,
            "short": self.short,
            "allowed_push_targets": [push_target.name for push_target in self.allowed_push_targets.all()],
        }


class AllowedPushTargetsModel(models.Model):
    """
    Abstract model providing allowed_push_targets field.

    This field stored in database as mask, masking fields from allowed push
    targets from parent.

    Abstract method _parent_allowed_push_targets() must be overridden.
    """

    masked_push_targets = models.ManyToManyField(PushTarget)

    class Meta:
        abstract = True

    def _parent_allowed_push_targets(self):
        """
        Returns allowed push targets from parent.

        This method must be overridden.
        """
        raise NotImplementedError()

    @property
    def allowed_push_targets(self):
        return self._parent_allowed_push_targets().exclude(id__in=self.masked_push_targets.all())

    @allowed_push_targets.setter
    def allowed_push_targets(self, value):
        self.masked_push_targets = self._parent_allowed_push_targets().exclude(id__in=value)

    def _allowed_push_target_names(self):
        return [push_target.name for push_target in self.allowed_push_targets]


class ProductVersion(AllowedPushTargetsModel):
    name                = models.CharField(max_length=200)
    short = models.CharField(max_length=200, validators=[
        RegexValidator(regex=RELEASE_SHORT_RE.pattern, message='Only accept lowercase letters, numbers or -')])
    version             = models.CharField(max_length=200, validators=[
        RegexValidator(regex=RELEASE_VERSION_RE.pattern, message='Only accept comma separated numbers or any text')])
    product             = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_version_id  = models.CharField(max_length=200)

    class Meta:
        unique_together = (("short", "version"))
        ordering = ("product_version_id", )

    def __unicode__(self):
        return self.product_version_id

    @property
    def active(self):
        return self.active_release_count > 0

    @property
    def release_count(self):
        return self.release_set.count()

    @property
    def active_release_count(self):
        return sum(1 for r in self.release_set.all() if r.active)

    def get_product_version_id(self):
        return u"%s-%s" % (self.short.lower(), self.version)

    def export(self):
        return {
            "name": self.name,
            "short": self.short,
            "version": self.version,
            "product_version_id": self.product_version_id,
            "product": self.product and self.product.short or None,
            "allowed_push_targets": self._allowed_push_target_names(),
        }

    def _parent_allowed_push_targets(self):
        return self.product.allowed_push_targets


@receiver(pre_save, sender=ProductVersion)
def populate_product_version_id(sender, instance, **kwargs):
    instance.product_version_id = instance.get_product_version_id()


class Release(AllowedPushTargetsModel):
    # release_id is populated by populate_release_id() pre_save hook
    release_id          = models.CharField(max_length=200, blank=False, unique=True)
    short = models.CharField(max_length=200, blank=False, validators=[
        RegexValidator(regex=RELEASE_SHORT_RE.pattern, message='Only accept lowercase letters, numbers or -')])
    version             = models.CharField(max_length=200, blank=False, validators=[
        RegexValidator(regex=RELEASE_VERSION_RE.pattern, message='Only accept comma separated numbers or any text')])
    name                = models.CharField(max_length=255, blank=False)
    release_type        = models.ForeignKey(ReleaseType, blank=False, db_index=True, on_delete=models.CASCADE)
    base_product        = models.ForeignKey(BaseProduct, null=True, blank=True, on_delete=models.CASCADE)
    active              = models.BooleanField(default=True)
    product_version     = models.ForeignKey(ProductVersion, blank=True, null=True, on_delete=models.CASCADE)
    integrated_with     = models.ForeignKey('self',
                                            null=True,
                                            blank=True,
                                            related_name='integrated_releases',
                                            on_delete=models.CASCADE)

    sigkey              = models.ForeignKey(SigKey, blank=True, null=True)
    allow_buildroot_push = models.BooleanField(default=False)
    allowed_debuginfo_services  = models.ManyToManyField(Service, blank=True)

    class Meta:
        unique_together = (
            ("short", "version", "release_type", "base_product"),
        )
        ordering = ("release_id", )

    def __unicode__(self):
        return u"%s" % self.release_id

    def is_active(self):
        return self.active is True

    def get_release_id(self):
        bp_dict = {}
        if self.base_product:
            bp_dict = {
                "bp_short": self.base_product.short.lower(),
                "bp_version": self.base_product.version,
                "bp_type": self.base_product.release_type.short,
            }
        return create_release_id(self.short.lower(), self.version, self.release_type.short, **bp_dict)

    def export(self):
        result = {
            "release_id": self.release_id,
            "short": self.short,
            "version": self.version,
            "name": self.name,
            "release_type": self.release_type.short,
            "active": self.active,
            "product_version": (self.product_version.product_version_id
                                if self.product_version else None),
            "integrated_with": (self.integrated_with.release_id
                                if self.integrated_with else None),
            "sigkey": (self.sigkey.key_id if self.sigkey else None),
            "allow_buildroot_push": self.allow_buildroot_push,
            "allowed_debuginfo_services": [],
            "allowed_push_targets": self._allowed_push_target_names(),
        }
        allowed_debuginfo_services = self.allowed_debuginfo_services.all()
        if allowed_debuginfo_services:
            for allowed_debuginfo in allowed_debuginfo_services:

pdc/apps/release/forms.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2015 Red Hat
# Licensed under The MIT License (MIT)
# http://opensource.org/licenses/MIT
#


import django.forms as forms
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _


class ReleaseSearchForm(forms.Form):
    search      = forms.CharField(required=False)
    disabled    = forms.BooleanField(required=False, label=_('Search in disabled releases'))

    def get_query(self, request):
        query = Q()
        if not self.is_valid():
            return query
        search = self.cleaned_data["search"]
        disabled = self.cleaned_data["disabled"]  # noqa

        if search:
            query |= Q(short__icontains=search)
            query |= Q(version__icontains=search)
            query |= Q(name__icontains=search)
            query |= Q(release_id__icontains=search)

        return query


class BaseProductSearchForm(forms.Form):
    search = forms.CharField(required=False)

    def get_query(self, request):
        query = Q()
        if not self.is_valid():
            return query
        search = self.cleaned_data["search"]

        if search:
            query |= Q(name__icontains=search)
            query |= Q(base_product_id__icontains=search)
            query |= Q(release_type__short__icontains=search)

        return query


class ProductSearchForm(forms.Form):
    search = forms.CharField(required=False)

    def get_query(self, request):
        query = Q()
        if not self.is_valid():
            return query
        search = self.cleaned_data["search"]

        if search:
            query |= Q(name__icontains=search)
            query |= Q(short__icontains=search)

        return query


class ProductVersionSearchForm(forms.Form):
    search = forms.CharField(required=False)

    def get_query(self, request):
        query = Q()
        if not self.is_valid():
            return query
        search = self.cleaned_data["search"]

        if search:
            query |= Q(name__icontains=search)
            query |= Q(product_version_id__icontains=search)

        return query

pdc/apps/release/templates/base_product_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h2 class="page-header">{% trans 'Base Product' %} #{{ base_product.id }}: {{ base_product }}</h2>

<dl class="details dl-horizontal">
    <dt>{% trans "ID" %}</dt>
    <dd>{{ base_product.id }}</dd>
    <dt>{% trans "Product Name" %}</dt>
    <dd>{{ base_product.name }}</dd>
    <dt>{% trans "Short Name" %}</dt>
    <dd>{{ base_product.short }}</dd>
    <dt>{% trans "Version" %}</dt>
    <dd>{{ base_product.version }}</dd>
    <dt>{% trans "Type" %}</dt>
    <dd>{{ base_product.release_type }}</dd>
</dl>

<h3 class="sub-header">{% trans 'Releases' %}</h3>
{% include "release_list_include.html" %}

{% endblock %}

pdc/apps/release/templates/base_product_list.html
{% extends "base.html" %}
{% load i18n %}
{% load pdctags %}

{% block content %}

<h2 class="page-header">
    {% trans "Base Products" %}
    {% include "help_button.html" %}
</h2>

<form method="GET" style="float: left;">
  {% csrf_token %}
  {{ form.search }}
  <input type="submit" value="{% trans "Search" %}" />
</form>

{% include "pagination.html" %}
{% include "base_product_list_include.html" %}
{% include "pagination.html" %}

{% helppopover %}
    <p>A <em>base product</em> represents the operating system on which a
    <a href="{% url "release/index" %}">release</a> is supposed to run on.</p>

    <p>In reality, base products often correspond to
    <a href="{% url "product_version/index" %}">product version</a>
    of that OS.</p>
{% endhelppopover %}

{% endblock %}

pdc/apps/release/templates/base_product_list_include.html
{% load i18n %}
<table class="table table-striped">
  <thead>
  <tr>
    <th>{% trans "Id" %}</th>
    <th>{% trans "Name" %}</th>
    <th>{% trans "Short Name" %}</th>
    <th>{% trans "Version" %}</th>
    <th>{% trans "Type" %}</th>
  </tr>
  </thead>
  <tbody>
{% for base_product in base_product_list %}
  <tr>
    <td><a href="{% url "base_product/detail/slug" base_product.base_product_id %}">{{ base_product }}</a></td>
    <td>{{ base_product.name }}</td>
    <td>{{ base_product.short }}</td>
    <td>{{ base_product.version }}</td>
    <td>{{ base_product.release_type }}</td>
  </tr>
{% endfor %}
  </tbody>
</table>

pdc/apps/release/templates/product_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h2 class="page-header">{% trans ' Product' %} #{{ product.id }}: {{ product.short }}</h2>

<dl class="details dl-horizontal">
    <dt>{% trans "ID" %}</dt>
    <dd>{{ product.id }}</dd>
    <dt>{% trans "Product Name" %}</dt>
    <dd>{{ product.name }}</dd>
    <dt>{% trans "Short Name" %}</dt>
    <dd>{{ product.short }}</dd>
    <dt>{% trans "Active" %}</dt>
    <dd>{{ product.active }}</dd>
</dl>

<h3 class="sub-header">{% trans 'Product Versions' %}</h3>
{% include "product_version_list_include.html" with product_version_list=product.productversion_set.all %}

{% endblock %}

pdc/apps/release/templates/product_list.html
{% extends "base.html" %}
{% load i18n %}
{% load pdctags %}

{% block content %}

<h2 class="page-header">
    {% trans "Products" %}
    {% include "help_button.html" %}
</h2>

<form method="GET" style="left">
  {% csrf_token %}
  {{ form.search }}
  <input type="submit" value="{% trans "Search" %}" />
</form>

{% include "product_list_include.html" %}

{% helppopover %}
    <p>In PDC, a <em>product</em> is just a group of
    <a href="{% url "product_version/index" %}">product versions</a> with the
    same name.</p>

    <p>Products are only used for grouping and organizing releases. They do not
    have any metadata on their own.</p>
{% endhelppopover %}

{% endblock %}

pdc/apps/release/templates/product_list_include.html
{% load i18n %}
<table class="table table-striped table-bordered">
 <thead>
  <tr>
    <th>{% trans "Short Name" %}</th>
    <th>{% trans "Name" %}</th>
    <th>
        <select id="active_filter" value= {{ page_size }}>
            <option value="All" selected>All products</option>
            <option value="Active">Active products</option>
            <option value="Inactive">Inactive products</option>
        </select>
    </th>
    <th>{% trans "Product Versions [active/total]" %}</th>
    <th>{% trans "Releases [active/total]" %}</th>
  </tr>
 </thead>
 <tbody>
{% for product in product_list %}
  <tr>
    <td><a href="{% url "product/detail/slug" product.short %}">{{ product.short }}</a></td>
    <td>{{ product.name }}</td>
    <td>
        {% if product.active %}
            Active
        {% else %}
            Inactive
        {% endif %}
    </td>
    <td>{{ product.active_product_version_count }} / {{ product.product_version_count }}</td>
    <td>{{ product.active_release_count }} / {{ product.release_count }}</td>
  </tr>
{% endfor %}
 </tbody>
</table>

pdc/apps/release/templates/product_pages.html
{% extends "base.html" %}

{% block content %}
<h3 class="page-header">Product information</h3>
<ul>
    <li><a href="{% url 'base_product/index' %}">Base Products</a></li>
    <li><a href="{% url 'product/index' %}">Products</a></li>
    <li><a href="{% url 'product_version/index' %}">Product Versions</a></li>
</li>
{% endblock %}

pdc/apps/release/templates/product_version_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h2 class="page-header">{% trans 'Product Version' %} #{{ product_version.id }}: {{ product_version.product_version_id }}</h2>

<dl class="details dl-horizontal">
    <dt>{% trans "ID" %}</dt>
    <dd>{{ product_version.id }}</dd>
    <dt>{% trans "Product Version ID" %}</dt>
    <dd>{{ product_version.product_version_id }}</dd>
    <dt>{% trans "Product Name" %}</dt>
    <dd>{{ product_version.name }}</dd>
    <dt>{% trans "Short Name" %}</dt>
    <dd>{{ product_version.short }}</dd>
    <dt>{% trans "Version" %}</dt>
    <dd>{{ product_version.version }}</dd>
    <dt>{% trans "Active" %}</dt>
    <dd>{{ product_version.active }}</dd>
</dl>

<h3 class="sub-header">{% trans 'Releases' %}</h3>
{% include "release_list_include.html" with release_list=product_version.release_set.all %}

{% endblock %}

pdc/apps/release/templates/product_version_list.html
{% extends "base.html" %}
{% load i18n %}
{% load pdctags %}

{% block content %}

<h2 class="page-header">
    {% trans "Product Versions" %}
    {% include "help_button.html" %}
</h2>

<form method="GET" style="left">
  {% csrf_token %}
  {{ form.search }}
  <input type="submit" value="{% trans "Search" %}" />
</form>

{% include "product_version_list_include.html" %}

{% helppopover %}
    <p>In PDC, a <em>product version</em> is just a group of
    <a href="{% url "release/index" %}">releases</a>
    with the same name and major version.</p>

    <p>Product versions are only used for grouping and organizing releases.
    They do not have any metadata on their own.</p>
{% endhelppopover %}

{% endblock %}

pdc/apps/release/templates/product_version_list_include.html
{% load i18n %}
<table class="table table-striped table-bordered">
 <thead>
  <tr>
    <th>{% trans "Id" %}</th>
    <th>{% trans "Name" %}</th>
    <th>{% trans "Short Name" %}</th>
    <th>{% trans "Version" %}</th>
    <th>
        <select id="active_filter" value= {{ page_size }}>
            <option value="All" selected>All product versions</option>
            <option value="Active">Active product versions</option>
            <option value="Inactive">Inactive product versions</option>
        </select>
    </th>
    <th>{% trans "Releases [active/total]" %}</th>
  </tr>
 </thead>
 <tbody>
{% for version in product_version_list %}
  <tr>
    <td><a href="{% url "product_version/detail/slug" version.product_version_id %}">{{ version.product_version_id }}</a></td>
    <td>{{ version.name }}</td>
    <td>{{ version.short }}</td>
    <td>{{ version.version }}</td>
    <td>
        {% if version.active %}
            Active
        {% else %}
            Inactive
        {% endif %}
    </td>
    <td>{{ version.active_release_count }} / {{ version.release_count }}</td>
  </tr>
{% endfor %}
 </tbody>
</table>

pdc/apps/release/templates/release_list.html
{% extends "base.html" %}
{% load i18n %}
{% load pdctags %}

{% block content %}

<h2 class="page-header">
    {% trans "Releases" %}
    {% include "help_button.html" %}
</h2>

<form method="GET" style="left">
  {% csrf_token %}
  {{ form.search }}
  <input type="submit" value="{% trans "Search" %}" />
</form>

{% include "release_list_include.html" %}

{% helppopover %}
    <p>A <em>release</em> is a collection of software with a unique identity
    and specific life cycle.</p>

    <p>Ideally, releases should be immutable. Once they are finished, the
    content and definition is not supposed to change.</p>

    <p>A release is divided into <em>variants</em>. These contain subset of
    release content targetted at a specific user, for example <em>server</em>
    or <em>workstation</em>. Each variant can be built for multiple
    architectures.</p>
{% endhelppopover %}

{% endblock %}

pdc/apps/release/templates/release_list_include.html
{% load i18n %}
<table class="table table-striped table-bordered">
 <thead>
  <tr>
    <th>{% trans "Release ID" %}</th>
    <th>{% trans "Name" %}</th>
    <th>{% trans "Short Name" %}</th>
    <th>{% trans "Version" %}</th>
    <th>{% trans "Base Product" %}</th>
    <th>{% trans "Product Version" %}</th>
    <th>{% trans "Release Type" %}</th>
    <th>
        <select id="active_filter" value= {{ page_size }}>
            <option value="All" selected>All releases</option>
            <option value="Active">Active releases</option>
            <option value="Inactive">Inactive releases</option>
        </select>
    </th>
  </tr>
 </thead>
 <tbody>
{% for release in release_list %}
  <tr>
    <td><a href="{% url "release/detail/slug" release.release_id %}">{{ release.release_id }}</a></td>
    <td>{{ release.name }}</td>
    <td>{{ release.short }}</td>
    <td>{{ release.version }}</td>
    <td>{% if release.base_product %}<a href="{% url "base_product/detail/slug" release.base_product.base_product_id %}">{{ release.base_product }}</a>{% endif %}</td>
    <td>
        {% if release.product_version %}
            <a href="{% url "product_version/detail/slug" release.product_version.product_version_id %}">
                {{ release.product_version }}
            </a>
        {% endif %}
    </td>
    <td>{{ release.release_type }}</td>
    <td>
        {% if release.active %}
            Active
        {% else %}
            Inactive
        {% endif %}
    </td>
  </tr>
{% endfor %}
 </tbody>
</table>