pdc/urls.py
#
# Copyright (c) 2015 Red Hat
# Licensed under The MIT License (MIT)
# http://opensource.org/licenses/MIT
#
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from pdc.apps.utils.SortedRouter import router
from django.utils.module_loading import autodiscover_modules

from pdc.apps.release.views import ReleaseListView, ReleaseDetailView
from pdc.apps.release.views import BaseProductListView, BaseProductDetailView
from pdc.apps.release.views import ProductListView, ProductDetailView
from pdc.apps.release.views import ProductVersionListView, ProductVersionDetailView
from pdc.apps.compose.views import ComposeListView, ComposeDetailView
from pdc.apps.compose.views import ComposeRPMListView, RPMOverrideFormView, ComposeImageListView
from pdc.apps.changeset.views import ChangesetListView, ChangesetDetailView
from pdc.apps.common import views as common_views
from pdc.apps.auth import views as auth_views
from pdc.apps.release import views as release_views


autodiscover_modules('routers')

urlpatterns = [
    url(r'^$', common_views.home, name='home'),

    # see details about configuring kerberos authentication in utils/auth.py
    url(r'^auth/krb5login$', auth_views.remoteuserlogin, name='auth/krb5login'),
    url(r'^auth/saml2login$', auth_views.remoteuserlogin, name='auth/saml2login'),
    url(r'^auth/logout$', auth_views.logout, name='auth/logout'),

    url(r'^admin/', admin.site.urls),
    url(r'^auth/profile/$', auth_views.user_profile, name='auth/profile'),
    url(r'^auth/refresh-ldap/$', auth_views.refresh_ldap_groups,
        name='auth/refresh_ldap'),

    url(r"^compose/$", ComposeListView.as_view(), name="compose/index"),
    url(r"^compose/(?P<id>\d+)/$", ComposeDetailView.as_view(), name="compose/detail"),

    url(r"^compose/(?P<id>\d+)/rpms/(?P<variant>[^/]+)/$", ComposeRPMListView.as_view(),
        name="compose/id/rpms/variant"),
    url(r"^compose/(?P<id>\d+)/rpms/(?P<variant>[^/]+)/(?P<arch>[^/]+)/$",
        ComposeRPMListView.as_view(), name="compose/id/rpms/variant/arch"),

    url(r"^compose/(?P<id>\d+)/images/(?P<variant>[^/]+)/$", ComposeImageListView.as_view(),
        name="compose/id/images/variant"),
    url(r"^compose/(?P<id>\d+)/images/(?P<variant>[^/]+)/(?P<arch>[^/]+)/$",
        ComposeImageListView.as_view(), name="compose/id/images/variant/arch"),

    url(r"^override/manage/(?P<release_id>[^/]+)/", RPMOverrideFormView.as_view(),
        name="override/manage"),

    url(r"^release/$", ReleaseListView.as_view(), name="release/index"),
    url(r"^release/(?P<id>\d+)/$", ReleaseDetailView.as_view(), name="release/detail"),
    url(r"^release/(?P<release_id>[^/]+)/$", ReleaseDetailView.as_view(), name="release/detail/slug"),

    url(r"^base-product/$", BaseProductListView.as_view(), name="base_product/index"),
    url(r"^base-product/(?P<id>\d+)/$", BaseProductDetailView.as_view(), name="base_product/detail"),
    url(r"^base-product/(?P<base_product_id>[^/]+)/$", BaseProductDetailView.as_view(), name="base_product/detail/slug"),

    url(r"^product/$", ProductListView.as_view(), name="product/index"),
    url(r"^product/(?P<id>\d+)/$", ProductDetailView.as_view(), name="product/detail"),
    url(r"^product/(?P<short>[^/]+)/$", ProductDetailView.as_view(), name="product/detail/slug"),
    url(r'^product-index/$', release_views.product_pages, name='product_pages'),

    url(r"^product-version/$",
        ProductVersionListView.as_view(),
        name="product_version/index"),
    url(r"^product-version/(?P<id>\d+)/$",
        ProductVersionDetailView.as_view(),
        name="product_version/detail"),
    url(r"^product-version/(?P<product_version_id>[^/]+)/$",
        ProductVersionDetailView.as_view(),
        name="product_version/detail/slug"),

    url(r"^%s%s/" % (settings.REST_API_URL, settings.REST_API_VERSION), include(router.urls)),
    url(r"^%sperms/" % settings.REST_API_URL, auth_views.api_perms, name="api-perms"),
    url(r'^changes/$', ChangesetListView.as_view(), name='changeset/list'),
    url(r'^changes/(?P<id>\d+)/$', ChangesetDetailView.as_view(), name='changeset/detail'),
]

handler404 = 'pdc.apps.common.views.handle404'

if settings.DEBUG:
    try:
        import debug_toolbar
    except ImportError:
        pass
    else:
        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

pdc/apps/compose/models.py
#
# Copyright (c) 2015 Red Hat
# Licensed under The MIT License (MIT)
# http://opensource.org/licenses/MIT
#
from django.core.exceptions import ValidationError
from django.db import models, connection, transaction
from django.db.utils import IntegrityError

from pdc.apps.common import models as common_models
from pdc.apps.common.hacks import add_returning

from productmd import composeinfo


class ComposeType(models.Model):
    name                = models.CharField(max_length=200, unique=True)

    def __unicode__(self):
        return u"%s" % self.name


class ComposeAcceptanceTestingState(models.Model):
    name                = models.CharField(max_length=200, unique=True)

    @staticmethod
    def get_untested():
        """Return default acceptance testing status."""
        return ComposeAcceptanceTestingState.objects.get(name='untested').pk

    def __unicode__(self):
        return u"%s" % self.name


class Compose(models.Model):
    release             = models.ForeignKey("release.Release", on_delete=models.CASCADE)
    compose_id          = models.CharField(max_length=200, unique=True)
    compose_date        = models.DateField()
    compose_type        = models.ForeignKey(ComposeType, on_delete=models.CASCADE)
    compose_respin      = models.PositiveIntegerField()
    compose_label       = models.CharField(max_length=200, null=True, blank=True)
    dt_imported         = models.DateTimeField(auto_now_add=True)
    deleted             = models.BooleanField(default=False)
    acceptance_testing  = models.ForeignKey(ComposeAcceptanceTestingState,
                                            default=ComposeAcceptanceTestingState.get_untested,
                                            on_delete=models.CASCADE)
    linked_releases     = models.ManyToManyField('release.Release', related_name='linked_composes', blank=True)

    class Meta:
        unique_together = (
            ("release", "compose_label"),
            ("release", "compose_date", "compose_type", "compose_respin"),
        )

    def __unicode__(self):
        if self.compose_label:
            return u"%s (%s)" % (self.compose_id, self.compose_label)
        return u"%s" % self.compose_id

    def export(self):
        return {
            "id": self.id,
            "compose_id": self.compose_id,
        }

    def __cmp__(self, another):
        """
        If both composes belong to the same release, they are compared by
        productmd. Otherwise they inherit the order from releases.
        """
        if self.release == another.release:
            return cmp(self._get_compose_info(), another._get_compose_info())
        return cmp(self.release.version_sort_key(), another.release.version_sort_key())

    def _get_compose_info(self):
        if not hasattr(self, '_compose_info'):
            self._compose_info = composeinfo.Compose(None)
            self._compose_info.id = self.compose_id
            self._compose_info.date = self.compose_date
            self._compose_info.respin = self.compose_respin
            self._compose_info.type = self.compose_type.name
        return self._compose_info

    @property
    def sigkeys(self):
        """
        Get a list of sigkey ids used in the compose.
        """
        sigkeys = common_models.SigKey.objects.filter(composerpm__variant_arch__variant__compose=self).distinct()
        result = sorted([i.key_id for i in sigkeys])
        if self.exist_unsigned:
            # detect unsigned RPMs
            result.append(None)
        return result

    @property
    def exist_unsigned(self):
        return ComposeRPM.objects.filter(variant_arch__variant__compose=self, sigkey=None).exists()

    def get_rpm_mapping(self, package, disable_overrides=False, release=None):
        """
        Get RPM mapping for this compose. This method returns a tuple. First
        element is the following mapping:

        {
            variant: {
                arch: {
                    rpm_name: [
                        {
                            arch: {
                                included: bool,
                                override: str
                            }
                        }
                    ]
                }
            }
        }

        Override tag is either 'orig' (ComposeRPM existed, no corresponding
        override), 'delete' (ComposeRPM exists, corresponding override excludes
        it) or 'create' (no ComposeRPM, include override).

        Included is False for not included packages, True otherwise.

        The second element of the tuple is a list of overrides that exclude
        non-existent package or include already existing package. All the
        overrides in this list have do_not_delete set. All overrides that could
        be in this list but can be deleted actually are deleted.

        If `release` argument is not specified, the release for which the
        compose was built will be used. The overrides will be taken from this
        release as well as variants and arches.
        """
        release = release or self.release
        mapping = ComposeRPMMapping()
        mapping.load_from_compose(self, package, release)
        overrides = OverrideRPM.objects.filter(release=release).filter(srpm_name=package)
        useless_overrides = []
        if not disable_overrides:
            useless_overrides = mapping.apply_overrides(overrides)

        return mapping, useless_overrides

    def get_rpms(self, rpm_name):
        """
        Find all RPMs with given name associated with this compose.
        """
        from pdc.apps.package.models import RPM
        return (RPM.objects.filter(name=rpm_name)
                .filter(composerpm__variant_arch__variant__compose=self)
                .distinct())

    def get_arch_testing_status(self):
        """
        Get a mapping of all variant.archs to their testing status.
        """
        result = {}
        for var_arch in VariantArch.objects.filter(
                variant__compose=self).select_related('variant', 'arch', 'rtt_testing_status'):
            variant = result.setdefault(var_arch.variant.variant_uid, {})
            variant[var_arch.arch.name] = var_arch.rtt_testing_status.name
        return result


def find_by(list, key, val):
    """Find a dict with given key=val pair in a list."""
    matches = [i for i in list if i[key] == val]
    return matches[0] if len(matches) == 1 else None


# This is duplicate by design
# these variants are a snapshot of real compose content
# -> no direct relation to release variants
class Variant(models.Model):
    compose             = models.ForeignKey(Compose, on_delete=models.CASCADE)
    variant_id          = models.CharField(max_length=100, blank=False)
    variant_uid         = models.CharField(max_length=200, blank=False)
    variant_name        = models.CharField(max_length=300, blank=False)
    variant_type        = models.ForeignKey("release.VariantType", related_name="compose_variant", on_delete=models.CASCADE)
    deleted             = models.BooleanField(default=False)

    class Meta:
        unique_together = (
            ("compose", "variant_uid"),
        )
        ordering = ("variant_uid", )

    def __unicode__(self):
        return u"%s" % (self.variant_uid, )

    @property
    def arches(self):
        return [i.arch for i in self.variantarch_set.all()]

    def export(self):
        return {
            'compose': self.compose.compose_id,
            'variant_id': self.variant_id,
            'variant_uid': self.variant_uid,
            'variant_name': self.variant_name,
            'variant_type': self.variant_type.name,
            'arches': [arch.name for arch in self.arches],
        }


class VariantArch(models.Model):
    variant             = models.ForeignKey(Variant, on_delete=models.CASCADE)
    arch                = models.ForeignKey("common.Arch", related_name="+", on_delete=models.CASCADE)
    rtt_testing_status  = models.ForeignKey(ComposeAcceptanceTestingState,
                                            default=ComposeAcceptanceTestingState.get_untested,
                                            on_delete=models.CASCADE)
    deleted             = models.BooleanField(default=False)

    class Meta:
        unique_together = (
            ("variant", "arch"),
        )
        ordering = ("variant", "arch")

    def __unicode__(self):
        return u"%s.%s" % (self.variant, self.arch)

    def export(self):
        return {
            "compose": self.variant.compose.compose_id,
            "variant": self.variant.variant_uid,
            "arch": self.arch.name,
            "rtt_testing_status": self.rtt_testing_status.name
        }


class Path(models.Model):
    """
    Class representing a path in compose. The same path can be reused in
    multiple places (e.g. in more RPMs).
    """
    path = models.CharField(max_length=4096, unique=True, blank=True)

    def __unicode__(self):
        return unicode(self.path)

    def export(self):
        return {
            "path": self.path
        }

    CACHE = {}

    @classmethod
    def get_cached_id(cls, value, create=False):
        return common_models.get_cached_id(cls, 'path', value, create)


class ComposeRPMManager(models.Manager):
    def get_queryset(self):
        return super(ComposeRPMManager, self).get_queryset().select_related("rpm", "sigkey", "content_category")


class ComposeRPM(models.Model):
    variant_arch        = models.ForeignKey(VariantArch, db_index=True, on_delete=models.CASCADE)
    rpm                 = models.ForeignKey("package.RPM", db_index=True, on_delete=models.CASCADE)
    sigkey              = models.ForeignKey("common.SigKey", null=True, blank=True, on_delete=models.CASCADE)
    content_category    = models.ForeignKey("repository.ContentCategory", on_delete=models.CASCADE)
    path                = models.ForeignKey(Path, on_delete=models.CASCADE)

    objects = ComposeRPMManager()

    class Meta:

pdc/apps/compose/templates/compose_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    {% if compose.deleted %}
        <h2 class="page-header"><del>{% trans 'Compose' %} #{{ compose.id }}: {{ compose.compose_id }}</del> <b>(Deleted)</b></h2>
    {% else %}
        <h2 class="page-header">{% trans 'Compose' %} #{{ compose.id }}: {{ compose.compose_id }}</h2>
    {% endif %}

<div class="row">
  <div class="col-md-6">
    <dl class="details dl-horizontal">
        <dt>{% trans "ID" %}</dt>
        <dd>{{ compose.id }}</dd>
        <dt>{% trans "Compose ID" %}</dt>
        <dd>{{ compose.compose_id }}</dd>
        <dt>{% trans "Release" %}</dt>
        <dd><a href="{% url "release/detail" compose.release_id %}">{{ compose.release }}</a></dd>
        <dt>{% trans "Date" %}</dt>
        <dd>{{ compose.compose_date|date:"Y-m-d" }}</dd>
        <dt>{% trans "Type" %}</dt>
        <dd>{{ compose.compose_type }}</dd>
        <dt>{% trans "Respin" %}</dt>
        <dd>{{ compose.compose_respin }}</dd>
        <dt>{% trans "Label" %}</dt>
        <dd>{% if compose.compose_label %}{{ compose.compose_label }}{% endif %}</dd>
        <dt>{% trans "Imported Date" %}</dt>
        <dd>{{ compose.dt_imported|date:"Y-m-d H:i:s" }}</dd>
        <dt>{% trans "SigKeys" %}</dt>
        <dd>{{ compose.sigkeys|join:", " }}
    </dl>
  </div>
  <div class="col-md-6">
    {% if compose.linked_releases.all %}
      <h3 class="sub-header">{% trans 'Linked releases' %}</h3>
      <ul>
        {% for release in compose.linked_releases.all %}
          <li>
            <a href="{% url "release/detail" release.id %}">{{ release }}</a>
          </li>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
</div>

<h3 class="sub-header">{% trans 'Variants' %}</h3>
<table class="table table-striped">
 <thead>
  <tr>
    <th>{% trans "UID" %}</th>
    <th>{% trans "ID" %}</th>
    <th>{% trans "Name" %}</th>
    <th>{% trans "Type" %}</th>
    <th>{% trans "Arches" %}</th>
  </tr>
 </thead>
 <tbody>
{% for variant in compose.variant_set.all %}
  <tr>
    <td>{{ variant.variant_uid }}</td>
    <td>{{ variant.variant_id }}</td>
    <td>{{ variant.variant_name }}</td>
    <td>{{ variant.variant_type }}</td>
    <td>
      <dl class="compose-links dl-horizontal">
        {% for arch in variant.arches %}
          <dt><strong>{{ arch.name }}</strong>:</dt>
          <dd>
              <a href="{% url "compose/id/rpms/variant/arch" compose.id variant.variant_uid arch.name %}">rpms</a>
              <a href="{% url "compose/id/images/variant/arch" compose.id variant.variant_uid arch.name %}">images</a>
          </dd>
        {% endfor %}
      </dl>
    </td>
  </tr>
{% endfor %}
 </tbody>
</table>

{% endblock %}

{% block head %}
<style>
.compose-links {
    margin-bottom: 0;
}
.compose-links.dl-horizontal dt {
    width: 8em;
    overflow: visible;
}
.compose-links.dl-horizontal dd {
    margin-left: 4.5em;
}
</style>
{% endblock %}

pdc/apps/compose/templates/compose_image_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h2 class="page-header">{% trans "Images" %} for {{compose}}</h2>
<h3 class="sub-header">{% trans "Variant" %}: {{ variant }}{% if arch %} - {{ arch }}{% endif %}</h3>

{% if not compose_image_list %}
    <p>There are no images here.</p>
{% else %}
    <div class="clearfix">
    <form method="GET" class="pull-left">
      {% csrf_token %}
      {{ form.search }}
      <input type="submit" value="{% trans "Search" %}" />
    </form>
    </div>

    {% include "pagination.html" %}
    {% include "compose_image_list_include.html" %}
    {% include "pagination.html" %}
{% endif %}

{% endblock %}

pdc/apps/compose/templates/compose_image_list_include.html
{% load i18n %}
{% load epochformat %}

{% for compose_image in compose_image_list %}
<h4>{{ compose_image.image.file_name }}</h4>
<div class="row">
<div class="col-md-4">
<dl class="details dl-horizontal">
    <dt>{% trans "Image Type" %}</dt><dd>{{ compose_image.image.image_type.name }}</dd>
    <dt>{% trans "Image Format" %}</dt><dd>{{ compose_image.image.image_format.name }}</dd>
    <dt>{% trans "Arch" %}</dt><dd>{{ compose_image.image.arch }}</dd>
    <dt>{% trans "Disc" %}</dt><dd>{{ compose_image.image.disc_number }} / {{ compose_image.image.disc_count }}</dd>
    <dt>{% trans "Mtime" %}</dt><dd>{{ compose_image.image.mtime }} ({{ compose_image.image.mtime|epochformat }})</dd>
    <dt>{% trans "Size" %}</dt><dd>{{ compose_image.image.size }} ({{ compose_image.image.size|filesizeformat }})</dd>
    <dt>{% trans "Bootable" %}</dt><dd>{{ compose_image.image.bootable }}</dd>
    <dt>{% trans "Volume ID" %}</dt><dd>{{ compose_image.image.volume_id }}</dd>
</dl>
</div>

<div class="col-md-8">
<dl class="details dl-horizontal">
    <dt>{% trans "Implant MD5" %}</dt><dd>{{ compose_image.image.implant_md5 }}</dd>
    <dt>{% trans "MD5 Checksum" %}</dt><dd>{{ compose_image.image.md5 }}</dd>
    <dt>{% trans "SHA1 Checksum" %}</dt><dd>{{ compose_image.image.sha1 }}</dd>
    <dt>{% trans "SHA256 Checksum" %}</dt><dd>{{ compose_image.image.sha256 }}</dd>
</dl>
</div>

</div>
{% endfor %}

pdc/apps/compose/templates/compose_list.html
{% extends "base.html" %}
{% load i18n %}
{% load pdctags %}

{% block content %}

<h2 class="page-header">
    {% trans "Composes" %}
    {% include "help_button.html" %}
</h2>

<form method="GET" style="float: left;">
  {% csrf_token %}
  {{ form.search }}
  <input type="submit" value="{% trans "Search" %}" />
</form>

{% include "pagination.html" %}
{% include "compose_list_include.html" %}
{% include "pagination.html" %}

{% helppopover %}
    <p>A <em>compose</em> is a snapshot of a
    <a href="{% url "release/index" %}">release</a> with unique identifier
    derived from release identifier and date.</p>

    <p>Each compose should consist of well-defined blocks; ideally defined by
    metadata like <code>.treeinfo</code>, repodata etc.</p>

    <p>Like a release, a compose is divided into <em>variants</em>.</p>
{% endhelppopover %}

{% endblock %}

pdc/apps/compose/templates/compose_list_include.html
{% load i18n %}
<table class="table table-striped">
 <thead>
  <tr>
    <th>{% trans "Compose ID" %}</th>
    <th>{% trans "Release" %}</th>
    <th>{% trans "Date" %}</th>
    <th>{% trans "Type" %}</th>
    <th>{% trans "Respin" %}</th>
    <th>{% trans "Label" %}</th>
    <th>{% trans "Imported Date" %}</th>
    <th>{% trans "Linked releases" %}</tr>
  </tr>
 </thead>
 <tbody>
{% for compose in compose_list %}
    {% if compose.deleted %}
        <tr class=deleted>
    {% else %}
        <tr>
    {% endif %}
    <td><a href="{% url "compose/detail" compose.id %}">{{ compose.compose_id }}</a></td>
    <td><a href="{% url "release/detail" compose.release_id %}">{{ compose.release }}</a></td>
    <td>{{ compose.compose_date|date:"Y-m-d" }}</td>
    <td>{{ compose.compose_type }}</td>
    <td>{{ compose.compose_respin }}</td>
    <td>{% if compose.compose_label %}{{ compose.compose_label }}{% endif %}</td>
    <td>{{ compose.dt_imported|date:"Y-m-d H:i:s" }}</td>
    <td>
      <ul class="list-inline">
        {% for release in compose.linked_releases.all %}
          <li><a href="{% url "release/detail" release.id %}">{{ release.release_id }}</a></li>
        {% endfor %}
      </ul>
    </td>
  </tr>
{% endfor %}
 </tbody>
</table>

pdc/apps/compose/templates/compose_rpm_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h2 class="page-header">{% trans "RPMs" %} for {{compose}}</h2>
<h3 class="sub-header">{% trans "Variant" %}: {{ variant }}{% if arch %} - {{ arch }}{% endif %}</h3>

<form method="GET" style="float: left;">
  {% csrf_token %}
  {{ form.search }}
  <input type="submit" value="{% trans "Search" %}" />
</form>

{% include "pagination.html" %}
{% include "compose_rpm_list_include.html" %}
{% include "pagination.html" %}

{% endblock %}

pdc/apps/compose/templates/compose_rpm_list_include.html
{% load i18n %}
<table class="table table-striped">
 <thead>
  <tr>
    <th>{% trans "RPM N-V-R.A" %}</th>
    <th>{% trans "Epoch" %}</th>
    <th>{% trans "SRPM" %}</th>
    <th>{% trans "SRPM N-E:V-R.A" %}</th>
    <th>{% trans "SigKey" %}</th>
  </tr>
 </thead>
 <tbody>
{% for compose_rpm in compose_rpm_list %}
  <tr>
    <td>{{ compose_rpm.rpm.name }}-{{ compose_rpm.rpm.version }}-{{ compose_rpm.rpm.release }}.{{ compose_rpm.rpm.arch }}</td>
    <td>{{ compose_rpm.rpm.epoch }}</td> 
    <td>{{ compose_rpm.rpm.srpm_name }}</td>
    <td>{% if compose_rpm.rpm.srpm_nevra %}{{ compose_rpm.rpm.srpm_nevra }}{% endif %}</td>
    <td>{{ compose_rpm.sigkey }}</td>
  </tr>
{% endfor %}
 </tbody>
</table>

pdc/apps/compose/templates/overrides_preview.html
{% extends "base.html" %}

{% block content %}

<h1 class="page-header">
    Override preview for <strong>{{ package }}</strong> in <strong>{{ release_id }}</strong>
</h1>

{% if has_errors %}
<div class="alert alert-danger" role="alert">
There are errors in the form.
</div>
{% endif %}


{% if num_forms > 0 %}

<form method="post">
{% csrf_token %}
{{ forms.management_form }}
<input type="hidden" name="preview_submit" value="True">
<input type="hidden" name="initial_data" value="{{ compressed }}">
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Variant</th>
            <th>Arch</th>
            <th>RPM Name</th>
            <th>RPM Arch</th>
            <th class="center-align">Include</th>
            <th class="center-align">Do not delete</th>
            <th>Comment</th>
        </tr>
    </thead>
    <tbody>
        {% for form in forms %}
            <tr class="bg-{% if form.initial.action == 'create' %}success{% else %}danger{% endif %}">
                <td>
                {% if form.initial.warning %}
                  <p class="form-control-static warning-sign" data-toggle="tooltip" data-placement="right" title="{{ form.initial.warning }}">
                    <span class="glyphicon glyphicon-exclamation-sign"></span>
                  </p>
                {% endif %}
                </td>
                <td>
                    {% for f in form.hidden_fields %}{{ f }}{% endfor %}
                    <p class="form-control-static">{{ form.variant.value }}</p>
                </td>
                <td>
                    <p class="form-control-static">{{ form.arch.value }}</p>
                </td>
                <td>
                    <p class="form-control-static">{{ form.rpm_name.value }}</p>
                </td>
                <td>
                    <p class="form-control-static">{{ form.rpm_arch.value }}</p>
                </td>
                <td class="center-align">
                    <p class="form-control-static">
                        {% if form.include.value %}
                            <span data-icon="plus">+</span>
                        {% else %}
                            <span data-icon="minus">-</span>
                        {% endif %}
                    </p>
                </td>
                <td class="center-align">{{ form.do_not_delete }}</td>
                <td>{{ form.comment }}</td>
            </tr>
            {% if form.non_field_errors %}
                <tr class="error-row text-danger bg-danger">
                    <td colspan=3 class="center-align">
                    {% for error in form.non_field_errors %}<p>{{ error }}</p>{% endfor %}
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
    </tbody>
</table>

<div class="panel panel-default">
  <div class="panel-heading" data-toggle="collapse" data-target="#previewBody">
    <h4 class="panel-title">Preview</h4>
  </div>
  <div id="previewBody" class="panel-collapse collapse">
    <div class="panel-body">
        <pre>{{ actions }}</pre>
    </div>
  </div>
</div>

<div class="btn-toolbar" role="toolbar">
    <button type="button" class="btn btn-link back-btn">Back to form</button>
    <input type="submit" class="btn btn-primary" value="Save">
</div>

</form>

{% else %}<!-- num_forms > 0 -->

<p>
No changes.
</p>

{% endif %}<!-- num_forms > 0 -->

{% endblock %}

{% block javascript %}
<script type="text/javascript">
(function() {
    "use strict";
    $(document).ready(function () {
        $(".back-btn").on('click', function () { window.history.back(); });
        $("input[type=text]").on('blur', function (event) {
            if ($(this).val()) {
                $(this).parents('tr').find('input[type=checkbox]').prop('checked', true);
            }
        });
        $(".center-align span").each(function () {
            var icon = $(this).data("icon");
            $(this).addClass("glyphicon").addClass("glyphicon-"+icon).text('');
        });
    });
    $('.warning-sign').tooltip({});
})();
</script>
{% endblock %}

{% block head %}
<style>
.center-align {
    text-align: center;
}
.error-row p {
    margin-bottom: 0;
}
.warning-sign {
    text-align: center;
    color: #A94442;
}
</style>
{% endblock %}